version: "3"
services:
  server:
    image: backend
    ports:
      - "8443:8443"
    environment:
      - spring.datasource.url=jdbc:mysql://hibernatejpa-mysqldb-1:3306/employeedb?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=employeedb
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234

networks:
  springmysql-net: